### ISSUE TITLE
Release 0.5.0 (checklist)

### ISSUE THREAD

**Issue by adamkewley** [ComputationalBiomechanicsLab/opensim-creator#719]
Checklist copied from (#675):

- [ ] Bump the version number in all the appropriate locations
- [ ] Edit the CHANGELOG to have a new `unreleased` section
- [ ] Run testsuite on DEBUG build with libASAN
- [ ] Manually spot-check the DEBUG+libASAN binary
- [ ] Spot-check the QA list (e.g. #499)
  - [ ] And maybe add some more automated tests, if time permits
- [ ] Upload binaries against the release
- [ ] Edit the release note on GitHub to be a shortened version of CHANGELOG that's more user-friendly
- [ ] Update Zenodo with the release
- [ ] Update `codemeta.json`, `CITATION.cff`, and anything in README that might be affected (#674)

**Comment by adamkewley** [comment]
Current known leaks from typical editor session (most will be fixed in OpenSim 4.5):

```text
SUMMARY: AddressSanitizer: 1555188 byte(s) leaked in 13343 allocation(s).
OpenSim::Object::updateFromXMLDocument()    55548
OpenSim::CMC_TaskSet::CMC_TaskSet    360
OpenSim::CoordinateSet::CoordinateSet(OpenSim::CoordinateSet const&)    761045
SimTK::TiXmlDocument::LoadFile(char const*, SimTK::TiXmlEncoding)    329597
OpenSim::CoordinateReference::CoordinateReference(OpenSim::CoordinateReference const&)    30448
OpenSim::AssemblySolver::updateCoordinateReference(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, double, double)    30576
OpenSim::Delp1990Muscle_Deprecated    16936
```
